module.exports = {
    "jwtPrivateKey": process.env.JWT_KEY,
    "refreshTokenSecret" : process.env.REFRESH_SECRET,
    "db": process.env.MONGODB_URI,
    "googleClientID": process.env.GOOGLE_CLIENT_ID,
    "googleClientSecret": process.env.GOOGLE_CLIENT_SECRET,
    "googleCallbackURL": process.env.GOOGLE_CALLBACK_URL,
    "cloudinaryName": process.env.CLOUDINARY_NAME,
    "cloudinaryAPIKey": process.env.CLOUDINARY_KEY,
    "cloudinarySecret": process.env.CLOUDINARY_SECRET,
    "cloudinaryRoot":  process.env.CLOUDINARY_ROOT,
    "redisURL": process.env.REDIS_URL,
    "sessionSecret" : process.env.SESSION_SECRET,
    "sendgridUser": process.env.SENDGRID_USER,
    "sendgridKey": process.env.SENDGRID_KEY,
    "mailUser": process.env.MAIL_USER,
    "mailPass": process.env.MAIL_PASS,
    "sesAccessKey": process.env.SES_ACCESS_KEY,
    "sesSecretKey": process.env.SES_SECRET_KEY,
    "twitterConsumerKey": process.env.TWITTER_CONSUMER_KEY,
    "twitterConsumerSecret": process.env.TWITTER_CONSUMER_SECRET,
    "twitterAccessTokenKey": process.env.TWITTER_TOKEN_KEY,
    "twitterAccessTokenSecret": process.env.TWITTER_TOKEN_SECRET,
    "clientUrl": process.env.CLIENT_URL,
}