//Common
export const SET_LOADING = 'SET_LOADING';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_AREA_LIST = 'SET_AREA_LIST';

//Home
export const SET_LATEST_JOBLIST = 'SET_LATEST_JOBLIST';

//Auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_OUT = 'SIGN_OUT';

//User
export const SET_AVATAR = 'SET_AVATAR';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_IMAGES = 'SET_IMAGES';
export const SET_UPLOADING_PHOTO_COUNT = 'SET_UPLOADING_PHOTO_COUNT';
export const ADD_SAVED_JOB = 'ADD_SAVED_JOB';
export const REMOVE_SAVED_JOB = 'REMOVE_SAVED_JOB';
export const ADD_APPLIED_JOB = 'ADD_APPLIED_JOB';
export const REMOVE_APPLIED_JOB = 'REMOVE_APPLIED_JOB';

//Job
export const SET_JOB_DETAILS = 'SET_JOB_DETAILS';
export const SET_JOB_SEARCH_FILTER = 'SET_JOB_SEARCH_FILTER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_JOB_SEARCH_RESULT = 'SET_JOB_SEARCH_RESULT';